//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaosTest.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChaosTest.Common.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChaosServiceEndpoint.
        /// </summary>
        public static string ChaosServiceEndpoint {
            get {
                return ResourceManager.GetString("ChaosServiceEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChaosServiceStateKey.
        /// </summary>
        public static string ChaosServiceStateKey {
            get {
                return ResourceManager.GetString("ChaosServiceStateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChaosTestServiceType.
        /// </summary>
        public static string ChaosTestServiceType {
            get {
                return ResourceManager.GetString("ChaosTestServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChaosTestWebServiceType.
        /// </summary>
        public static string ChaosTestWebServiceType {
            get {
                return ResourceManager.GetString("ChaosTestWebServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventCountKey.
        /// </summary>
        public static string EventCountKey {
            get {
                return ResourceManager.GetString("EventCountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceInitializationParameters is not of type StatefulServiceInitializationParameters.
        /// </summary>
        public static string IncorrectTypeMessage {
            get {
                return ResourceManager.GetString("IncorrectTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedEventsKey.
        /// </summary>
        public static string SavedEventsKey {
            get {
                return ResourceManager.GetString("SavedEventsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTimeKey.
        /// </summary>
        public static string StartTimeKey {
            get {
                return ResourceManager.GetString("StartTimeKey", resourceCulture);
            }
        }
    }
}
